server:
  port: 8080

spring:
  application:
    name: goods-service
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 100
      #获取连接时最大等待时间
      max-wait: 60000
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000
  cloud:
    nacos:
      server-addr: 47.115.162.144:8848


goodsservice:
  webdav:
    username: oomall
    password: 123465
    baseUrl: http://localhost:8080/web/
brandservice:
  webdav:
    username: oomall
    password: 123465
    baseUrl: http://localhost:8080/web/
shopservice:
  webdav:
    username: oomall
    password: 123465
    baseUrl: http://localhost:8080/web/

mybatis:
  # 将包中的类添加为类型别名
  type-aliases-package: com.xmu.oomall.domain
  # mapper.xml所在的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 是否开启驼峰命名自动映射，即从经典数据库列名 A_COLUMN 映射到经典 Java 属性名 aColumn。
    map-underscore-to-camel-case: true

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql

dubbo:
  application:
    name: dubbo-goods
  scan:
    base-packages: cn.edu.xmu.goods.client
  registry:
    address: nacos://47.115.162.144:8848
  protocol:
    name: dubbo
    port: 28091